name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the most recent version of our code
        uses: actions/checkout@v1

      - name: Setup both Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install all of our dependencies
        run: npm ci

      - name: Run all of our Unit Tests
        run: npm test
